server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;  # <-- 이 줄이 핵심입니다! (파일이 없으면 무조건 index.html로 토스)
    }
}